name: norm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install norminette
        run: |
          git clone https://github.com/42Paris/norminette.git norminette
          cd norminette
          bundle
      - name: Norm
        run: cd norminette && ./norminette.rb ../*.c && ./norminette.rb ../*.h